---
- name: Contiv Node | Set cert flag
  set_fact:
    contiv_certs_provided: "{{ contiv_etcd_ca_cert_file is defined or contiv_etcd_cert_file is defined or contiv_etcd_key_file is defined or contiv_etcd_endpoints is defined | bool }}"

- name: Contiv Node | Error if invalid cert arguments
  fail:
    msg: "Must provide all or none for the following etcd params: contiv_etcd_ca_cert_file, contiv_etcd_cert_file, contiv_etcd_key_file, contiv_etcd_endpoints"
  when:
  - contiv_certs_provided
  - not (contiv_etcd_ca_cert_file is defined and contiv_etcd_cert_file is defined and contiv_etcd_key_file is defined and contiv_etcd_endpoints is defined)

- name: Contiv Node | Set etcd cert location facts
  when: not contiv_certs_provided
  set_fact:
    contiv_etcd_ca_cert_file: "/etc/origin/master/master.etcd-ca.crt"
    contiv_etcd_cert_file: "/etc/origin/master/master.etcd-client.crt"
    contiv_etcd_key_file: "/etc/origin/master/master.etcd-client.key"
    #{{ openshift_master_etcd_hosts | lib_utils_oo_etcd_host_urls(l_use_ssl, openshift_master_etcd_port) }}
    # contiv_etcd_endpoints: "{{ hostvars[groups.oo_first_master.0].openshift_master_etcd_urls | join(',') }}"
    contiv_etcd_endpoints: |-
      {% for n in range( openshift_master_etcd_hosts | length) -%}
        contiv{{ n }}=https://{{ openshift_master_etcd_hosts[n-1] }}:2380{% if not loop.last %},{% endif %}
      {%- endfor %}
      
- name: Contiv Node | Error if no certs set.
  fail:
    msg: "Invalid etcd configuration for contiv."
  when: item is not defined or item == ''
  with_items:
  - contiv_etcd_ca_cert_file
  - contiv_etcd_cert_file
  - contiv_etcd_key_file
  - contiv_etcd_endpoints

- name: Contiv Node | Assure the contiv certs are present
  stat:
    path: "{{ item }}"
    get_checksum: false
    get_attributes: false
    get_mime: false
  with_items:
  - "{{ contiv_etcd_ca_cert_file }}"
  - "{{ contiv_etcd_cert_file }}"
  - "{{ contiv_etcd_key_file }}"

# - include_tasks: etcd_config.yml

- name: Create secret
  oc_secret:
    name: contiv-etcd-secrets
    state: present
    namespace: contiv-infra
    files:
    - name: etcd-key
      path: "{{ contiv_etcd_key_file }}"
    - name: etcd-cert
      path: "{{ contiv_etcd_cert_file }}"
    - name: etcd-ca
      path: "{{ contiv_etcd_ca_cert_file }}"
  run_once: true

- name: Create secret
  oc_secret:
    name: contiv-master-secrets
    state: present
    namespace: contiv-infra
    files:
    - name: master-key
      path: "{{ openshift.common.config_base }}/master/master.server.key"
    - name: master-cert
      path: "{{ openshift.common.config_base }}/master/master.server.crt"
    - name: master-ca
      path: "{{ openshift.common.config_base }}/master/ca.crt"
  run_once: true

 