---
- include_tasks: download_bins.yml
- include_tasks: ovs.yml

- include_tasks: netplugin_firewalld.yml
  when: contiv_has_firewalld

- include_tasks: netplugin_iptables.yml
  when: not contiv_has_firewalld and contiv_has_iptables

- name: Netplugin | Ensure localhost entry correct in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1.*'
    line: '127.0.0.1 localhost localhost.localdomain'
    state: present

- name: Netplugin | Remove incorrect localhost entry in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^::1. localhost '
    line: '::1 '
    state: absent

# - name: Netplugin | Create Netplugin bin symlink
#   file:
#     src: "{{ contiv_current_release_directory }}/netplugin"
#     dest: "{{ contiv_bin_dir }}/netplugin"
#     state: link
#     force: yes

- name: Netplugin | Ensure contiv_cni_bin_dir exists
  file:
    path: "{{ contiv_cni_bin_dir }}"
    recurse: yes
    state: directory

# - name: Netplugin | Create CNI bin symlink
#   file:
#     src: "{{ contiv_current_release_directory }}/contivk8s"
#     dest: "{{ contiv_cni_bin_dir }}/contivk8s"
#     state: link
#     force: yes

- name: Netplugin | Copy CNI loopback bin
  copy:
    src: "{{ contiv_cni_download_dir }}/loopback"
    dest: "{{ contiv_cni_bin_dir }}/loopback"
    remote_src: True
    mode: 0755

- name: Netplugin | Ensure contiv_kube_plugin_dir and cni/net.d directories exist
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ contiv_kube_plugin_dir }}"
    - "/etc/cni/net.d"

- name: Netplugin | Ensure contiv directories exist
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ contiv_releases_directory }}/bin"
    - "{{ contiv_releases_directory }}/config"

- name: Netplugin | Create contiv config file
  template:
    src: contiv.cfg.j2
    dest: "{{ contiv_releases_directory }}/config/contiv.json"

- name: Netplugin | Copy contiv_cni.conf file
  copy:
    src: contiv_cni.conf
    dest: "{{ item }}"
  with_items:
    - "/etc/cni/net.d"
# notify: restart kubelet

# - name: Netplugin | Make sure docker proxy setting exists
#   lineinfile:
#     dest: /etc/sysconfig/docker-network
#     regexp: '^https_proxy.*'
#     line: 'https_proxy="{{ contiv_https_proxy }}"'
#     state: present
#   register: docker_updated

