---
- include_tasks: ovs.yml
  when: contiv_netplugin_driver == "ovs"

- name: systemd reload
  command: systemctl daemon-reload
  when: docker_updated is changed

- name: Netplugin | Flush handlers
  meta: flush_handlers

- name: Netplugin | Restart docker
  service:
    name: "{{ contiv_openshift_docker_service_name }}"
    state: restarted
  when: docker_updated is changed
  register: l_docker_restart_docker_in_contiv_result
  until: not (l_docker_restart_docker_in_contiv_result is failed)
  retries: 3
  delay: 30

- name: Netplugin | Enable Netplugin
  service:
    name: netplugin
    enabled: yes

- name: Netplugin | Start Netplugin
  service:
    name: netplugin
    state: started
# notify: restart kubelet
