---
- name: API ns | Create temp directory for doing work
  command: mktemp -d /tmp/openshift-contiv-XXXXXX
  register: mktemp
  changed_when: False
  # For things that pass temp files between steps, we want to make sure they
  # run on the same node.
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true

- name: Contiv ns | Create contiv-infra-ns from template
  template:
    src: contiv-infra-ns.yaml.j2
    dest: "{{ mktemp.stdout }}/contiv-infra-ns.yml"
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true

- name: Contiv ns | Add namespace
  oc_obj:
    state: present
    kind: namespace
    name: contiv-infra
    files:
      - "{{ mktemp.stdout }}/contiv-infra-ns.yml"
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true  

- name: API ns | Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true
