---
- name: Old version cleanup | Delete old forward [in] iptables rules
  iptables:
    state: absent
    chain: FORWARD
    in_interface: "{{ item }}"
    jump: ACCEPT
    comment: "{{ item }} FORWARD input"
  with_items:
    - contivh0
    - contivh1
  notify: Save iptables rules

- name: Old version cleanup | Delete old forward [out] iptables rules
  iptables:
    state: absent
    chain: FORWARD
    out_interface: "{{ item }}"
    jump: ACCEPT
    comment: "{{ item }} FORWARD output"
  with_items:
    - contivh0
    - contivh1
  notify: Save iptables rules

- name: Old version cleanup | Delete old input iptables rules
  iptables:
    state: absent
    chain: INPUT
    protocol: "{{ item.split('/')[1] }}"
    match: "{{ item.split('/')[1] }}"
    destination_port: "{{ item.split('/')[0] }}"
    comment: "{{ item.split('/')[2] }}"
    jump: ACCEPT
  with_items:
    - "53/udp/contiv dns"
    - "4789/udp/netplugin vxlan 4789"
    - "8472/udp/netplugin vxlan 8472"
    - "9003/tcp/contiv"
    - "9002/tcp/contiv"
    - "9001/tcp/contiv"
    - "9999/tcp/contiv"
    - "10000/tcp/Contiv auth proxy service (10000)"
  notify: Save iptables rules

- name: Netmaster IPtables | Delete k8s service forward rule
  iptables:
    state: absent
    table: nat
    chain: OUTPUT
    protocol: "{{ item.split('/')[0] }}"
    source: "{{ contiv_h1_ip }}"
    destination: "{{ contiv_kube_master_api }}"
    destination_port: "{{ item.split('/')[1] }}"
    out_interface: "contivh1"
    jump: "DNAT"
    to_destination: "{{ item.split('/')[2] }}"
    comment: contiv master kubeservice
  loop: "{{ contiv_netmaster_kube_svc }}"
  notify: Save iptables rules
