---

- name: Kube-router | oc adm policy add-scc-to-user privileged system:serviceaccount:kube-router-infra:kube-router-node
  oc_adm_policy_user:
    user: system:serviceaccount:kube-router-infra:kube-router
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Kube-router | Create temp directory
  command: mktemp -d /tmp/openshift-ansible-XXXXXXX
  register: mktemp
  changed_when: False
      
- name: Kube Router ns | Create kube-router-infra-ns from template
  template:
    src: kube-router-infra-ns.yaml.j2
    dest: "{{ mktemp.stdout }}/kube-router-infra-ns.yml"
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true

- name: Kube Router ns | Add namespace
  oc_obj:
    state: present
    kind: namespace
    name: kube-router-infra
    files:
      - "{{ mktemp.stdout }}/kube-router-infra-ns.yml"
  delegate_to: "{{ groups.oo_masters_to_config.0 }}"
  run_once: true 

- name: Kube-router | Write Kube-router v3
  template:
    dest: "{{ mktemp.stdout }}/kube-router.yml"
    src: kube-router.yml.j2

- name: Kube-router | Launch Kube-router
  run_once: true
  command: >
    {{ openshift_client_binary }} apply
    -f {{ mktemp.stdout }}/kube-router.yml
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
  register: kube_router_create_output
  failed_when: "kube_router_create_output.rc != 0"
  changed_when: "('created' in kube_router_create_output.stdout) or ('configured' in kube_router_create_output.stdout)"

- name: Kube-router | Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
