---


- name: Kube-router | oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:kube-router-node
  oc_adm_policy_user:
    user: system:serviceaccount:kube-system:kube-router
    resource_kind: scc
    resource_name: privileged
    state: present

- name: Kube-router | Set default selector for kube-system
  command: >
    {{ openshift_client_binary }}
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
    annotate  ns kube-system openshift.io/node-selector="" --overwrite

- name: Kube-router | Create temp directory
  command: mktemp -d /tmp/openshift-ansible-XXXXXXX
  register: mktemp
  changed_when: False

- name: Kube-router | Write Kube-router v3
  template:
    dest: "{{ mktemp.stdout }}/kube-router.yml"
    src: kube-router.yml.j2

- name: Kube-router | Launch Kube-router
  run_once: true
  command: >
    {{ openshift_client_binary }} apply
    -f {{ mktemp.stdout }}/kube-router.yml
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
  register: kube-router_create_output
  failed_when: "kube-router_create_output.rc != 0"
  changed_when: "('created' in kube-router_create_output.stdout) or ('configured' in kube-router_create_output.stdout)"

- name: Kube-router | Delete temp directory
  file:
    name: "{{ mktemp.stdout }}"
    state: absent
  changed_when: False
